package com.yongjie.ZhiJianSbpt.model.sysBase;

// Generated 2016-7-13 9:56:09 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

;

/**
 * Menu generated by hbm2java
 */
public class Menu {
    private long id;//主键
    private String menuName;//菜单名
    private String menuLink;//菜单连接地址
    private long parentId;//父亲ID，默认值0
    private String parentPath;//树路径
    private Integer depth;//树深度，默认1
    private Integer paiXu;//排序，默认值0
    private Integer flag;//0:申报端 1：审批端
    private String caoR;//操作人
    private Date caoDate;//操作区域
    private Integer menuGroup;//菜单分组

    public Menu() {
    }

    public Menu(long id) {
        this.id = id;
    }

    public Menu(long id, String menuName, String menuLink, long parentId, String parentPath, Integer depth,
                Integer paiXu, Integer flag, String caoR, Date caoDate, Integer menuGroup) {
        super();
        this.id = id;
        this.menuName = menuName;
        this.menuLink = menuLink;
        this.parentId = parentId;
        this.parentPath = parentPath;
        this.depth = depth;
        this.paiXu = paiXu;
        this.flag = flag;
        this.caoR = caoR;
        this.caoDate = caoDate;
        this.menuGroup = menuGroup;
    }

    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public String getMenuName() {
        return this.menuName;
    }

    public void setMenuName(String menuName) {
        this.menuName = menuName;
    }

    public String getMenuLink() {
        return this.menuLink;
    }

    public void setMenuLink(String menuLink) {
        this.menuLink = menuLink;
    }

    public long getParentId() {
        return this.parentId;
    }

    public void setParentId(long parentId) {
        this.parentId = parentId;
    }

    public String getParentPath() {
        return this.parentPath;
    }

    public void setParentPath(String parentPath) {
        this.parentPath = parentPath;
    }

    public Integer getDepth() {
        return this.depth;
    }

    public void setDepth(Integer depth) {
        this.depth = depth;
    }

    public Integer getPaiXu() {
        return this.paiXu;
    }

    public void setPaiXu(Integer paiXu) {
        this.paiXu = paiXu;
    }

    public Integer getFlag() {
        return this.flag;
    }

    public void setFlag(Integer flag) {
        this.flag = flag;
    }

    public String getCaoR() {
        return this.caoR;
    }

    public void setCaoR(String caoR) {
        this.caoR = caoR;
    }

    public Date getCaoDate() {
        return this.caoDate;
    }

    public void setCaoDate(Date caoDate) {
        this.caoDate = caoDate;
    }

    public Integer getMenuGroup() {
        return menuGroup;
    }

    public void setMenuGroup(Integer menuGroup) {
        this.menuGroup = menuGroup;
    }
}
