package com.yongjie.ZhiJianSbpt.model.flowBase;

// Generated 2016-9-1 14:59:26 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * YjBizFuJianList generated by hbm2java
 */
public class YjFlowFuJianList {
    private long id;
    private Long flowId;
    private String sqsType;
    private String fileName;
    private String fileExtense;//限制文件类型
    private String fileMaxSize;//限制文件大小，单位Mb
    private String memo;
    private Integer groupId;
    private Integer paiXu;
    private String caoR;
    private Date caoDate;

    public YjFlowFuJianList() {
    }

    public YjFlowFuJianList(long id) {
        this.id = id;
    }

    public YjFlowFuJianList(long id, Long flowId, String sqsType,
                            String fileName, String fileExtense, String memo,
                            Integer groupId, Integer paiXu, String caoR, Date caoDate) {
        this.id = id;
        this.flowId = flowId;
        this.sqsType = sqsType;
        this.fileName = fileName;
        this.fileExtense = fileExtense;
        this.memo = memo;
        this.groupId = groupId;
        this.paiXu = paiXu;
        this.caoR = caoR;
        this.caoDate = caoDate;
    }

    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public Long getFlowId() {
        return flowId;
    }

    public void setFlowId(Long flowId) {
        this.flowId = flowId;
    }

    public String getSqsType() {
        return this.sqsType;
    }

    public void setSqsType(String sqsType) {
        this.sqsType = sqsType;
    }

    public String getFileName() {
        return this.fileName;
    }

    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    public String getFileExtense() {
        return this.fileExtense;
    }

    public void setFileExtense(String fileExtense) {
        this.fileExtense = fileExtense;
    }

    public String getMemo() {
        return this.memo;
    }

    public void setMemo(String memo) {
        this.memo = memo;
    }

    public Integer getGroupId() {
        return this.groupId;
    }

    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }

    public Integer getPaiXu() {
        return this.paiXu;
    }

    public void setPaiXu(Integer paiXu) {
        this.paiXu = paiXu;
    }

    public String getCaoR() {
        return this.caoR;
    }

    public void setCaoR(String caoR) {
        this.caoR = caoR;
    }

    public Date getCaoDate() {
        return this.caoDate;
    }

    public void setCaoDate(Date caoDate) {
        this.caoDate = caoDate;
    }

    public String getFileMaxSize() {
        return fileMaxSize;
    }

    public void setFileMaxSize(String fileMaxSize) {
        this.fileMaxSize = fileMaxSize;
    }

}
