package com.yongjie.ZhiJianSbpt.model.flowBase;

// Generated 2016-9-9 10:22:15 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * YjFlowInstWenShu generated by hbm2java
 */
public class YjFlowInstWenShu {

    private long id;
    private String nodeId;
    private Long flowId;
    private Long flowInstId;
    private Long bizId;
    private String wenHao;
    private String fileTitle;
    private String filePath;
    private Long fileSize;
    private String extense;
    private String tiaoMa;
    private Integer isgz;
    private Integer flag;
    private Long fileTypeId;
    private Integer type;
    private Integer paixu;
    private String czr;
    private Date czDate;

    /**
     * 网络文件路径,即上报端的路径
     */
    private String netWorkPath;

    /**
     * 流水号
     */
    private String serialNumber;

    private String license_code;//证照推送标识码
    private String auth_code;//证照推送查验码

    private String lng;//经度
    private String lat;//纬度

    private String imgAddress;//照片拍摄地址
    private String imgTime;
    private String bglx; //自我声明业务类型
    private Date pzDate; //核准日期
    private Date sqDate; //申请日期
    private String sqlx; //申请类型

    public YjFlowInstWenShu() {
    }

    public YjFlowInstWenShu(long id, String nodeId, Long flowId, Long flowInstId, Long bizId, String wenHao, String fileTitle, String filePath, Long fileSize, String extense, String tiaoMa, Integer isgz, Integer flag, Long fileTypeId, Integer type, Integer paixu, String czr, Date czDate, String netWorkPath, String serialNumber, String license_code, String auth_code, String lng, String lat, String imgAddress, String imgTime, String bglx, Date pzDate, Date sqDate, String sqlx) {
        this.id = id;
        this.nodeId = nodeId;
        this.flowId = flowId;
        this.flowInstId = flowInstId;
        this.bizId = bizId;
        this.wenHao = wenHao;
        this.fileTitle = fileTitle;
        this.filePath = filePath;
        this.fileSize = fileSize;
        this.extense = extense;
        this.tiaoMa = tiaoMa;
        this.isgz = isgz;
        this.flag = flag;
        this.fileTypeId = fileTypeId;
        this.type = type;
        this.paixu = paixu;
        this.czr = czr;
        this.czDate = czDate;
        this.netWorkPath = netWorkPath;
        this.serialNumber = serialNumber;
        this.license_code = license_code;
        this.auth_code = auth_code;
        this.lng = lng;
        this.lat = lat;
        this.imgAddress = imgAddress;
        this.imgTime = imgTime;
        this.bglx = bglx;
        this.pzDate = pzDate;
        this.sqDate = sqDate;
        this.sqlx = sqlx;
    }

    public String getSqlx() {
        return sqlx;
    }

    public void setSqlx(String sqlx) {
        this.sqlx = sqlx;
    }

    public String getBglx() {
        return bglx;
    }

    public void setBglx(String bglx) {
        this.bglx = bglx;
    }

    public Date getPzDate() {
        return pzDate;
    }

    public void setPzDate(Date pzDate) {
        this.pzDate = pzDate;
    }

    public Date getSqDate() {
        return sqDate;
    }

    public void setSqDate(Date sqDate) {
        this.sqDate = sqDate;
    }

    public String getNetWorkPath() {
        return netWorkPath;
    }

    public void setNetWorkPath(String netWorkPath) {
        this.netWorkPath = netWorkPath;
    }

    public String getSerialNumber() {
        return serialNumber;
    }

    public void setSerialNumber(String serialNumber) {
        this.serialNumber = serialNumber;
    }

    public String getLng() {
        return lng;
    }

    public void setLng(String lng) {
        this.lng = lng;
    }

    public String getLat() {
        return lat;
    }

    public void setLat(String lat) {
        this.lat = lat;
    }

    public String getImgAddress() {
        return imgAddress;
    }

    public void setImgAddress(String imgAddress) {
        this.imgAddress = imgAddress;
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public String getNodeId() {
        return nodeId;
    }

    public void setNodeId(String nodeId) {
        this.nodeId = nodeId;
    }

    public Long getFlowId() {
        return flowId;
    }

    public void setFlowId(Long flowId) {
        this.flowId = flowId;
    }

    public Long getFlowInstId() {
        return flowInstId;
    }

    public void setFlowInstId(Long flowInstId) {
        this.flowInstId = flowInstId;
    }

    public Long getBizId() {
        return bizId;
    }

    public void setBizId(Long bizId) {
        this.bizId = bizId;
    }

    public String getWenHao() {
        return wenHao;
    }

    public void setWenHao(String wenHao) {
        this.wenHao = wenHao;
    }

    public String getFileTitle() {
        return fileTitle;
    }

    public void setFileTitle(String fileTitle) {
        this.fileTitle = fileTitle;
    }

    public String getFilePath() {
        return filePath;
    }

    public void setFilePath(String filePath) {
        this.filePath = filePath;
    }

    public Long getFileSize() {
        return fileSize;
    }

    public void setFileSize(Long fileSize) {
        this.fileSize = fileSize;
    }

    public String getExtense() {
        return extense;
    }

    public void setExtense(String extense) {
        this.extense = extense;
    }

    public String getTiaoMa() {
        return tiaoMa;
    }

    public void setTiaoMa(String tiaoMa) {
        this.tiaoMa = tiaoMa;
    }

    public Integer getIsgz() {
        return isgz;
    }

    public void setIsgz(Integer isgz) {
        this.isgz = isgz;
    }

    public Integer getFlag() {
        return flag;
    }

    public void setFlag(Integer flag) {
        this.flag = flag;
    }

    public Long getFileTypeId() {
        return fileTypeId;
    }

    public void setFileTypeId(Long fileTypeId) {
        this.fileTypeId = fileTypeId;
    }

    public Integer getType() {
        return type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    public Integer getPaixu() {
        return paixu;
    }

    public void setPaixu(Integer paixu) {
        this.paixu = paixu;
    }

    public String getCzr() {
        return czr;
    }

    public void setCzr(String czr) {
        this.czr = czr;
    }

    public Date getCzDate() {
        return czDate;
    }

    public void setCzDate(Date czDate) {
        this.czDate = czDate;
    }

    public String getLicense_code() {
        return license_code;
    }

    public void setLicense_code(String license_code) {
        this.license_code = license_code;
    }

    public String getAuth_code() {
        return auth_code;
    }

    public void setAuth_code(String auth_code) {
        this.auth_code = auth_code;
    }

    public String getImgTime() {
        return imgTime;
    }

    public void setImgTime(String imgTime) {
        this.imgTime = imgTime;
    }

}
