package com.yongjie.ZhiJianSbpt.startFlow.model;

// Generated 2016-9-1 14:59:26 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * YjFlowInst generated by hbm2java
 */
public class YjFlowInst {

    private long id;
    private Long flowId;
    private Integer currentState;
    private String flowInstName;
    private String caoR;
    private Date caoDate;

    public YjFlowInst() {
    }

    public YjFlowInst(long id) {
        this.id = id;
    }

    public YjFlowInst(long id, Long flowId, Integer currentState,
                      String flowInstName, String caoR, Date caoDate) {
        this.id = id;
        this.flowId = flowId;
        this.currentState = currentState;
        this.flowInstName = flowInstName;
        this.caoR = caoR;
        this.caoDate = caoDate;
    }

    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public Long getFlowId() {
        return this.flowId;
    }

    public void setFlowId(Long flowId) {
        this.flowId = flowId;
    }

    public Integer getCurrentState() {
        return this.currentState;
    }

    public void setCurrentState(Integer currentState) {
        this.currentState = currentState;
    }

    public String getFlowInstName() {
        return this.flowInstName;
    }

    public void setFlowInstName(String flowInstName) {
        this.flowInstName = flowInstName;
    }

    public String getCaoR() {
        return this.caoR;
    }

    public void setCaoR(String caoR) {
        this.caoR = caoR;
    }

    public Date getCaoDate() {
        return this.caoDate;
    }

    public void setCaoDate(Date caoDate) {
        this.caoDate = caoDate;
    }

}
