package com.yongjie.ZhiJianSbpt.startFlow.model;

// Generated 2016-9-1 14:59:26 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * YjFlowInstParticipant generated by hbm2java
 */
public class YjFlowInstParticipant {

    private long id;
    private Long flowId;
    private Long flowInstId;
    private String nodeId;
    private Integer participantType;
    private String participant;
    private String caoR;
    private Date caoDate;

    public YjFlowInstParticipant() {
    }

    public YjFlowInstParticipant(long id) {
        this.id = id;
    }

    public YjFlowInstParticipant(long id, Long flowId, Long flowInstId,
                                 String nodeId, Integer participantType,
                                 String participant, String caoR, Date caoDate) {
        this.id = id;
        this.flowId = flowId;
        this.flowInstId = flowInstId;
        this.nodeId = nodeId;
        this.participantType = participantType;
        this.participant = participant;
        this.caoR = caoR;
        this.caoDate = caoDate;
    }

    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public Long getFlowId() {
        return this.flowId;
    }

    public void setFlowId(Long flowId) {
        this.flowId = flowId;
    }

    public Long getFlowInstId() {
        return this.flowInstId;
    }

    public void setFlowInstId(Long flowInstId) {
        this.flowInstId = flowInstId;
    }

    public String getNodeId() {
        return this.nodeId;
    }

    public void setNodeId(String nodeId) {
        this.nodeId = nodeId;
    }

    public Integer getParticipantType() {
        return this.participantType;
    }

    public void setParticipantType(Integer participantType) {
        this.participantType = participantType;
    }

    public String getParticipant() {
        return this.participant;
    }

    public void setParticipant(String participant) {
        this.participant = participant;
    }

    public String getCaoR() {
        return this.caoR;
    }

    public void setCaoR(String caoR) {
        this.caoR = caoR;
    }

    public Date getCaoDate() {
        return this.caoDate;
    }

    public void setCaoDate(Date caoDate) {
        this.caoDate = caoDate;
    }

}
