package com.yongjie.ZhiJianSbpt.startFlow.model;

// Generated 2016-9-1 14:59:26 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * YjNodeInst generated by hbm2java
 */
public class YjNodeInst {

    private long id;
    private Long flowId;
    private Long flowInstId;
    private String nodeId;
    private String nodeInstName;
    private Integer currentState;
    private String caoR;
    private Date caoDate;

    public YjNodeInst() {
    }

    public YjNodeInst(long id) {
        this.id = id;
    }

    public YjNodeInst(long id, Long flowId, Long flowInstId,
                      String nodeId, String nodeInstName,
                      Integer currentState, String caoR, Date caoDate) {
        this.id = id;
        this.flowId = flowId;
        this.flowInstId = flowInstId;
        this.nodeId = nodeId;
        this.nodeInstName = nodeInstName;
        this.currentState = currentState;
        this.caoR = caoR;
        this.caoDate = caoDate;
    }

    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public Long getFlowId() {
        return this.flowId;
    }

    public void setFlowId(Long flowId) {
        this.flowId = flowId;
    }

    public Long getFlowInstId() {
        return this.flowInstId;
    }

    public void setFlowInstId(Long flowInstId) {
        this.flowInstId = flowInstId;
    }

    public String getNodeId() {
        return this.nodeId;
    }

    public void setNodeId(String nodeId) {
        this.nodeId = nodeId;
    }

    public String getNodeInstName() {
        return this.nodeInstName;
    }

    public void setNodeInstName(String nodeInstName) {
        this.nodeInstName = nodeInstName;
    }

    public Integer getCurrentState() {
        return this.currentState;
    }

    public void setCurrentState(Integer currentState) {
        this.currentState = currentState;
    }

    public String getCaoR() {
        return this.caoR;
    }

    public void setCaoR(String caoR) {
        this.caoR = caoR;
    }

    public Date getCaoDate() {
        return this.caoDate;
    }

    public void setCaoDate(Date caoDate) {
        this.caoDate = caoDate;
    }

}
