package com.yongjie.ZhiJianSbpt.startFlow.model;

// Generated 2016-9-1 14:59:26 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * YjWorkItem generated by hbm2java
 */
public class YjWorkItem {

    private long id;
    private Long flowId;
    private Long flowInstId;
    private Long nodeInstId;
    private String participant;
    private Integer currentState;
    private String caoR;
    private Date caoDate;

    public YjWorkItem() {
    }

    public YjWorkItem(long id) {
        this.id = id;
    }

    public YjWorkItem(long id, Long flowId, Long flowInstId, Long nodeInstId,
                      String participant, Integer currentState, String caoR,
                      Date caoDate) {
        this.id = id;
        this.flowId = flowId;
        this.flowInstId = flowInstId;
        this.nodeInstId = nodeInstId;
        this.participant = participant;
        this.currentState = currentState;
        this.caoR = caoR;
        this.caoDate = caoDate;
    }

    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public Long getFlowId() {
        return this.flowId;
    }

    public void setFlowId(Long flowId) {
        this.flowId = flowId;
    }

    public Long getFlowInstId() {
        return this.flowInstId;
    }

    public void setFlowInstId(Long flowInstId) {
        this.flowInstId = flowInstId;
    }

    public Long getNodeInstId() {
        return this.nodeInstId;
    }

    public void setNodeInstId(Long nodeInstId) {
        this.nodeInstId = nodeInstId;
    }

    public String getParticipant() {
        return this.participant;
    }

    public void setParticipant(String participant) {
        this.participant = participant;
    }

    public Integer getCurrentState() {
        return this.currentState;
    }

    public void setCurrentState(Integer currentState) {
        this.currentState = currentState;
    }

    public String getCaoR() {
        return this.caoR;
    }

    public void setCaoR(String caoR) {
        this.caoR = caoR;
    }

    public Date getCaoDate() {
        return this.caoDate;
    }

    public void setCaoDate(Date caoDate) {
        this.caoDate = caoDate;
    }

}
