package com.yongjie.ZhiJianSbpt.model;

// Generated 2016-8-10 14:53:19 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * AccountSbpt generated by hbm2java
 */
public class AccountSbpt {

    private long id;
    private String userName;
    private String password;
    private int flag;
    private String qymc;
    private String zcdz;
    private int areaId;
    private String zzjgdm;
    private String fddbr;
    private String fddbrdh;
    private String lxr;
    private String lxdh;
    private String email;
    private String yzbm;
    private int isAction;
    private Date caoDate;
    private String userId;//用来存放云政用户的userid
    private Integer isDlf;    //是否是独立法人        0：独立法人    1：非独立法人
    private String newShxydm; //新社会信用代码   社会信用代码-uuid
    private Integer sfbs;        //是否是本省用户			1： 不是    其他值： 是
    private String wsXzqh;        // 外省用户的行政区划

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public int getFlag() {
        return flag;
    }

    public void setFlag(int flag) {
        this.flag = flag;
    }

    public String getQymc() {
        return qymc;
    }

    public void setQymc(String qymc) {
        this.qymc = qymc;
    }

    public String getZcdz() {
        return zcdz;
    }

    public void setZcdz(String zcdz) {
        this.zcdz = zcdz;
    }

    public int getAreaId() {
        return areaId;
    }

    public void setAreaId(int areaId) {
        this.areaId = areaId;
    }

    public String getZzjgdm() {
        return zzjgdm;
    }

    public void setZzjgdm(String zzjgdm) {
        this.zzjgdm = zzjgdm;
    }

    public String getFddbr() {
        return fddbr;
    }

    public void setFddbr(String fddbr) {
        this.fddbr = fddbr;
    }

    public String getFddbrdh() {
        return fddbrdh;
    }

    public void setFddbrdh(String fddbrdh) {
        this.fddbrdh = fddbrdh;
    }

    public String getLxr() {
        return lxr;
    }

    public void setLxr(String lxr) {
        this.lxr = lxr;
    }

    public String getLxdh() {
        return lxdh;
    }

    public void setLxdh(String lxdh) {
        this.lxdh = lxdh;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getYzbm() {
        return yzbm;
    }

    public void setYzbm(String yzbm) {
        this.yzbm = yzbm;
    }

    public int getIsAction() {
        return isAction;
    }

    public void setIsAction(int isAction) {
        this.isAction = isAction;
    }

    public Date getCaoDate() {
        return caoDate;
    }

    public void setCaoDate(Date caoDate) {
        this.caoDate = caoDate;
    }

    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public Integer getIsDlf() {
        return isDlf;
    }

    public void setIsDlf(Integer isDlf) {
        this.isDlf = isDlf;
    }

    public String getNewShxydm() {
        return newShxydm;
    }

    public void setNewShxydm(String newShxydm) {
        this.newShxydm = newShxydm;
    }

    public Integer getSfbs() {
        return sfbs;
    }

    public void setSfbs(Integer sfbs) {
        this.sfbs = sfbs;
    }

    public String getWsXzqh() {
        return wsXzqh;
    }

    public void setWsXzqh(String wsXzqh) {
        this.wsXzqh = wsXzqh;
    }
}
